<?php

namespace App\Services;

use App\Models\MikrotikConnection;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use RuntimeException;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class RadiusClientsSynchronizer
{
    public function __construct(private Filesystem $filesystem) {}

    /**
     * @throws FileNotFoundException
     * @throws ProcessFailedException
     */
    public function sync(): void
    {
        $connections = MikrotikConnection::query()
            ->where('is_active', true)
            ->whereNotNull('radius_secret')
            ->with('wgPeer')
            ->get();

        $payload = $this->buildClientsPayload($connections);
        $path = (string) config('radius.clients_path');

        $directory = dirname($path);
        if (! $this->filesystem->isDirectory($directory)) {
            $parent = dirname($directory);
            if ($this->filesystem->isDirectory($parent) && $this->filesystem->isReadable($parent)) {
                throw new RuntimeException("Direktori {$directory} belum ada. Buat manual dan beri izin tulis untuk webserver.");
            }

            throw new RuntimeException("Tidak dapat mengakses direktori {$directory}. Periksa izin untuk webserver.");
        } elseif (! $this->filesystem->isWritable($directory)) {
            throw new RuntimeException("Direktori {$directory} tidak writable untuk sinkronisasi FreeRADIUS.");
        }

        if ($this->filesystem->exists($path) && ! $this->filesystem->isWritable($path)) {
            throw new RuntimeException("File {$path} tidak writable untuk sinkronisasi FreeRADIUS.");
        }
        $this->filesystem->put($path, $payload);

        $command = (string) config('radius.reload_command');
        if ($command !== '') {
            $process = Process::fromShellCommandline($command);
            $process->run();

            if (! $process->isSuccessful()) {
                throw new ProcessFailedException($process);
            }
        }
    }

    private function buildClientsPayload(Collection $connections): string
    {
        $lines = [
            '# Generated by Laravel - do not edit manually',
        ];

        foreach ($connections as $connection) {
            $shortName = Str::slug($connection->name, '_') ?: 'mikrotik_'.$connection->id;
            $secret = addslashes($connection->radius_secret);

            $wgPeer = $connection->wgPeer;
            $nasIp = ($wgPeer?->is_active && $wgPeer->vpn_ip)
                ? $wgPeer->vpn_ip
                : $connection->host;
            $nasNote = ($wgPeer?->is_active && $wgPeer->vpn_ip)
                ? '# NAS IP via WireGuard tunnel'
                : '# NAS IP: direct';

            $lines[] = $nasNote;
            $lines[] = "client {$shortName} {";
            $lines[] = "    ipaddr = {$nasIp}";
            $lines[] = "    secret = \"{$secret}\"";
            $lines[] = "    shortname = {$shortName}";
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
